[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488A6DC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f6b5e40a8100278e0df90208125401c8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488A6F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f6b5e40a8100278e0df90208125401c8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024C488A6940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f6b5e40a8100278e0df90208125401c8